Pb- 32 add, getById and getAllByUserId
tel-ran-de/phonebook-m9-1 pull request #30
Opened 2020-09-16 18:08 UTC by bolokadze

2020-09-18 14:20 UTC, sharf85 requested changes

2020-09-18 14:20 UTC, sharf85 commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/ContactController.java
> +        this.addressMapper = addressMapper;
You dont use the mappers. Please clean the code from unnecessary things

2020-09-18 14:20 UTC, sharf85 commented on phonebook-api/src/main/java/com/telran/phonebookapi/controller/ContactController.java
> +        } else {
unnecessary else

2020-09-21 18:32 UTC, bolokadze commented
When trying to getAddressById or allAddressesByContactId fields take wrong places, when to getEmailById or allEmailsByContactId field Email is null

2020-09-22 17:16 UTC, sharf85 submitted a review, later dismissed

2020-09-22 17:57 UTC, sharf85 approved these changes

2020-09-22 17:58 UTC, merged